language: php

matrix:
    include:
        -   php: 7.1
        -   php: 7.2
        -   php: 7.3
        -   php: 7.4snapshot
            env: PHP_CS_FIXER_IGNORE_ENV=1
        -   php: nightly
            env: PHP_CS_FIXER_IGNORE_ENV=1
    fast_finish: true
    allow_failures:
        - php: nightly

cache:
    directories:
        - vendor/
        - tools/

before_script:
    - composer install --optimize-autoloader --no-suggest --quiet

script:
    - make phpcs
    - make test
