language: php
php:
    - 7.1
    - 7.2

matrix:
    fast_finish: true

cache:
    directories:
        - vendor/
        - tools/

before_script:
    - composer install --optimize-autoloader --no-suggest --quiet

script:
  - make phpcs
  - mkdir -p build/logs
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then make test-coverage  ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '7.1' ]]; then make test ; fi

after_script:
 - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then php vendor/bin/php-coveralls -v ; fi
