language: php
php:
    - 7.1
    - 7.2

matrix:
    fast_finish: true

cache:
    directories:
        - vendor/
        - tools/

before_script:
    - composer install --optimize-autoloader --no-suggest --quiet

script:
    - make phpcs
    - make test
